apiVersion: v1
kind: ConfigMap
metadata:
  name: riptide-collector-app
data:
  RIPTIDE_LOG_LEVEL: "INFO"
  RIPTIDE_CONFIG_PATH: "/etc/riptide-collector/riptide.json"
  RIPTIDE_TEAM_KEYS_PATH: "/etc/riptide-collector-team-keys/team-keys.json"
  RIPTIDE_CONFIG_RELOAD_SECONDS: "30"
