apiVersion: v1
kind: ConfigMap
metadata:
  name: riptide-collector-app
data:
  RIPTIDE_LOG_LEVEL: "INFO"
  RIPTIDE_CATALOG_PATH: "/etc/riptide-collector/service-catalog.json"
  RIPTIDE_CATALOG_RELOAD_SECONDS: "30"
