apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - configmap-app.yaml
  - job-migrate.yaml

configMapGenerator:
  - name: riptide-collector-service-catalog
    files:
      - service-catalog.json=../../config/service-catalog.json

images:
  - name: riptide-collector
    newName: image-registry.openshift-image-registry.svc:5000/riptide/riptide-collector
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/name: riptide-collector
      app.kubernetes.io/part-of: riptide
      app.kubernetes.io/component: collector
